CREATE TABLE USER (
 ID INT (5) NOT NULL AUTO_INCREMENT,
 EMAIL VARCHAR (30) NOT NULL,
 PASSWORD VARCHAR (30) NOT NULL,
 PRIMARY KEY ( ID )
);
CREATE TABLE CONTACT (
 ID INT (5) NOT NULL AUTO_INCREMENT,
 USER_ID INT (5) NOT NULL,
 CELLPHONE_NUMBER VARCHAR (12) NOT NULL,
 EMAIL VARCHAR (30) NOT NULL,
 PRIMARY KEY ( ID )
);
CREATE TABLE TRIP (
 ID INT (5) NOT NULL AUTO_INCREMENT,
 USER_ID INT (5) NULL,
 END_TIME DATETIME NULL,
 PRIMARY KEY ( ID )
);
CREATE TABLE POSITION (
 ID INT (5) NOT NULL AUTO_INCREMENT,
 TRIP_ID INT(5) NULL,
 LATITUDE DOUBLE NOT NULL,
 LONGITUDE DOUBLE NOT NULL,
 DATE_TIME DATETIME NOT NULL,
 PRIMARY KEY ( id )
);

ALTER TABLE `CONTACT` ADD CONSTRAINT `fk_user_id` FOREIGN KEY ( `user_id` ) REFERENCES `USER` ( `id` ) ;
ALTER TABLE `TRIP` ADD CONSTRAINT `fk_user_id` FOREIGN KEY ( `user_id` ) REFERENCES `USER` ( `id` ) ;
ALTER TABLE `POSITION` ADD CONSTRAINT `fk_trip_id` FOREIGN KEY ( `trip_id` ) REFERENCES `TRIP` ( `id` ) ;